import os
import sys
import asyncio
from pathlib import Path
from dotenv import load_dotenv
from rubpy import Client

# Fix for Windows (not needed on Linux, but harmless)
if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

load_dotenv()

# Session file name, default to 'rubika_session' or from env
SESSION_FILE = os.getenv("RUBIKA_SESSION", "rubika_session")

def session_exists() -> bool:
    """Check if the session file exists."""
    return Path(SESSION_FILE).exists()

def create_dummy_file():
    """Create a small dummy Python file to upload."""
    content = '''# This is a dummy file generated by GitHub Actions
print("Hello from Rubika!")
'''
    path = Path("dummy_script.py")
    path.write_text(content, encoding="utf-8")
    return str(path)

def upload_to_me(file_path: str):
    """Upload a file to Saved Messages (me)."""
    client = Client(name=SESSION_FILE)  # rubpy uses the file name without extension internally, but the file must be present as-is
    try:
        client.start()
        client.send_document("me", file_path, caption="📎 Sent from GitHub Actions")
        print("✅ File uploaded successfully.")
    except Exception as e:
        print(f"❌ Upload failed: {e}")
    finally:
        try:
            client.disconnect()
        except Exception:
            pass

def main():
    if not session_exists():
        print("❌ Session file not found. Make sure the secret is correctly set.")
        sys.exit(1)

    dummy_file = create_dummy_file()
    upload_to_me(dummy_file)

if __name__ == "__main__":
    main()
